# Page settings

baseurl = "//ecstatic-clarke-f63514.netlify.com/"
languageCode = "en-us"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-27962903-3"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Resume for Prakash Prasad"
    author = "Prakash Prasad"
    title = "Prakash Prasad's Resume"

# Theme styles

    # The original template comes with 6 color schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and color scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Prakash Prasad"
        tagline = "Software Architect / Tech Lead"
        avatar = "latest_profile_pic_500x500.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: prakash@prakashprasad.com"
        title = "prakash@prakashprasad.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+4794263344"
        title = "+4794263344"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//projects.shader.works"
        title = "projects.shader.works"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/prakashprasad"
        title = "linkedin.com/in/prakashprasad"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/indusninja"
        title = "github.com/indusninja"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/indusninja"
        title = "@indusninja"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "MS in Media Technology & Games"
        college = "IT University of Copenhagen"
        dates = "2009 - 2011"

        [[params.education.list]]
        degree = "BS in Computer Science"
        college = "Coastal Carolina University"
        dates = "2004 - 2005"

        [[params.education.list]]
        degree = "BS in Computer Science"
        college = "Ansal Institute of Technology"
        dates = "2002 - 2004"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

        [[params.language.list]]
        language = "Hindi"
        level = "Native"

        [[params.language.list]]
        language = "Norwegian"
        level = "Reading"
        # level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Climbing"

        [[params.interests.list]]
        interest = "Photography"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "I believe that the primary role of a software developer is to 'solve problems'. Want to order a pizza from your phone? Want to show your love for cats to the internet? Want to keep track of things to do? Well, a software developer can solve those for you.\n\nThe most basic problems are the ones that are defined by someone to most detailed level, and a developer is asked to 'just make it work'. However, other problems are more complex and harder to solve:\n\n- Our delivery cycle is very slow because our development team needs many steps before making a release,\n\n- Our software is often buggy,\n\n- We often wildly miss our deadlines,\n\n- We have a hard time keeping hold of development team,\n\n- Our software performs badly,\n\n- Our software systems are very complex and need a lot of time and energy to change direction etc.\n\nI find these broader issues in software development to be very interesting. A solid foundation of architectural foresight and planning, clear and transparent communication, and a good development workflow would be my three wishes for any team to navigate through most of these issues - something that I've learned first-hand from my experience in game development.\n\nI try to feel the pulse of common pitfalls in software development, and am ever curious about new trends which can alleviate those issues. However, there are many more problems for me to explore in software development, and there is much more to learn. The question is... where to next?"

# I'm a game programmer with many projects under by belt. 
    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "System Developer"
        dates = "2018 - Present"
        company = "If P&C, Oslo"
        details = "For a multi-national company like 'If', the focus is often on designing homogenous processes (and consequently software) to simplify complexity and lower costs. In this particular case, this means a focus on decomposing the company's legacy monolith application into a more flexible and maintainable microservice architecture. My role in this mission statement is to:\n\n- Split up monolith functionality into microservices, and promote these into Azure.\n\n- Design and implement any new services to be cloud native.\n\n- Fullstack development of C# backend systems along with React based frontends."

        [[params.jobs.list]]
        position = "Game Programmer"
        dates = "2016 - 2018"
        company = "The Future Group, Oslo"
        details = "The Future Group develops tightly coupled products for television broadcasting using **[Unreal Engine 4](https://www.unrealengine.com/en-US/what-is-unreal-engine-4)**. Their products vary from *content for broadcasts*, to *second screen mobile apps* augmenting those broadcasts. Their first show, **Lost in Time**, aired in April 2017 in Norway. While working at there, my duties were:\n\n- As technical lead my role was to liaise with various stakeholders in production of the games - workflow (setting up *[Perforce SCM](https://www.perforce.com/products/helix-core)*, and *[Jenkins](https://jenkins.io/)* build pipelines), architecture, QA, etc.\n\n- When getting closer to the delivery deadline, my focus shifted to performance testing, and optimizations for PC and mobile platforms (iOS and Android).\n\n- Architect of a messaging service providing data interoperability for several internal and external products."

        [[params.jobs.list]]
        position = "Game Programmer"
        dates = "2011 - 2016"
        company = "Reto-Moto, Copenhagen"
        details = "Heroes & Generals is a free-to-play, massively multiplayer online (MMO) game that combines real-time strategy (RTS) with first person shooter (FPS) gameplay. The game’s backend is an event driven architecture, which uses [protocol buffers](https://developers.google.com/protocol-buffers/) for passing messages.\n\nAt the game's core is a 'WarServer' which provides most of the game's services such as *login*, *matchmaking*, *statistics*, *metrics*, *transactions*, *handling results of games*, etc. These services are consumed by various parts of the game - *web client*, *FPS game*, and *mobile client*.\n\n- Implement handlers that service game clients. For example, *buying soldiers*, *equipping/un-equipping items on soldiers*, *execute movement orders for units*, etc.\n\n- The backend architecture uses an in-memory key-value data storage. However, one issue with such a system was handling multiple updated to the same object before a transaction is finalized. I implemented an interface that would allow this functionality by caching intermediate results.\n\n- Some of the game's immutable data had to be accessed through the in-memory data storage system, which was hurting performance. I implemented a cache layer that improved access to this data by about 10 times.\n\n- Data Management: Handling tasks related to management, upgrade, upkeep, and trouble-shooting on the game's dataset which is stored on SQL database servers."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "These are some of the side projects that I've worked on in my free time. For more info about these and other such projects visit **[projects.shader.works](https://projects.shader.works/)**"

        [[params.projects.list]]
        title = "Stay, Good Dog!"
        url = "https://github.com/indusninja/stay-good-dog"
        tagline = "Game that is all about a friendship between a dog and his owner. You play as the dog, and you must find your way back home to the arms of your owner."

        [[params.projects.list]]
        title = "What's mine is NOT yours"
        url = "https://github.com/indusninja/flatmates"
        tagline = "2D multiplayer game where each player tries to hoard as much items in a shared apartment."

        [[params.projects.list]]
        title = "The Gods Must be Crazy"
        url = "https://github.com/indusninja/godsmustbecrazy"
        tagline = "Game where players have to try to destroy life in a given solar system by utilizing celestial mechanics (i.e. motion of objects in space, under the influence of objects in space)."

        [[params.projects.list]]
        title = "Monkey of Puppets"
        url = "https://github.com/indusninja/monkeyofpuppets"
        tagline = "Puzzle game where players have to sneak past the enemies, find the key and get to the door to escape the current level. And do it all over again in the next level."

        [[params.projects.list]]
        title = "Snowball Fight"
        url = "https://bitbucket.org/klauskk/snowball"
        tagline = "3D multiplayer game where players fight across a snow covered playground in teams."

        [[params.projects.list]]
        title = "Gnome Engine"
        url = "https://github.com/indusninja/gnome-engine"
        tagline = "3D game engine (for OpenGL 3.x), designed for games with physics for balls."

        [[params.projects.list]]
        title = "Bocce"
        url = "https://github.com/indusninja/bocce"
        tagline = "2D game engine (for XNA framework)."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "C#"
        level = "100%"

        [[params.skills.list]]
        skill = "C++"
        level = "90%"
                
        [[params.skills.list]]
        skill = "Javascript"
        level = "70%"
                
        [[params.skills.list]]
        skill = "React"
        level = "60%"

        [[params.skills.list]]
        skill = "Unreal Engine"
        level = "90%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
