version: '3'

services:
  hugo:
    image: solidnerd/hugo
    container_name: hugo-resume
    restart: always
    volumes:
      - .:/hugo
    ports:
      - 1313:1313
    command: server -w --bind 0.0.0.0